### ISSUE TITLE
Dispose is not called in task CE

### ISSUE THREAD

**Issue by dustinmoris** [giraffe-fsharp/Giraffe.Tasks#1]
Originally posted by @nikonthethird in https://github.com/giraffe-fsharp/Giraffe/issues/219

----------

Using the latest available version of Giraffe on Nuget, the following never prints `"DISPOSED"`:

```fsharp
open Giraffe
open Giraffe.Tasks
open System

let testHandler : HttpHandler = fun next ctx -> task {
    use x = { new IDisposable with member _this.Dispose () = printfn "DISPOSED" }
    do printfn "BEFORE DISPOSE"
    return! text "Hi" next ctx
}
```

The line `"BEFORE DISPOSE"` is printed in the console, but `"DISPOSED"` never is. What's going on here?

**Comment by dustinmoris** [comment]
Originally posted by @nikonthethird in https://github.com/giraffe-fsharp/Giraffe/issues/219

---------

The output window shows the following:

```
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
BEFORE DISPOSE
Loaded 'C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.webutilities\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 173.8979ms 200 text/plain

```

**Comment by dustinmoris** [comment]
@nikonthethird

You are right, there's something wrong, because I just tested the following:

```fsharp
let testHandler : HttpHandler =
    fun next ctx ->
        task {
            use x =
                {
                    new IDisposable
                    with member _this.Dispose () = printfn "DISPOSED 1"
                }
            do printfn "BEFORE DISPOSE 1"
            return! text "Hi 1" next ctx
        }

let testHandler2 : HttpHandler =
    fun next ctx ->
        use x =
            {
                new IDisposable
                with member _this.Dispose () = printfn "DISPOSED 2"
            }
        do printfn "BEFORE DISPOSE 2"
        text "Hi 2" next ctx
```

The `testHandler` doesn't dispose the object whereas `testHandler2` does invoke `Dispose()`. The only difference is the usage of the `task {}` CE.

I had a look at the current implementation of `using` inside the Task CE and came across this implementation:

```fsharp
/// Implements a using statement that disposes `disp` after `body` has completed.
    let inline using (disp : #IDisposable) (body : _ -> Step<'a>) =
        // A using statement is just a try/finally with the finally block disposing if non-null.
        tryFinally
            (fun () -> body disp)
            (fun () -> if not (isNull (box disp)) then disp.Dispose())
```

So a using is only using a Try Finally... which means that we should see the same bug with a try finally in the task CE:

```fsharp
let testHandler3 : HttpHandler =
    fun next ctx ->
        task {
            let x =
                {
                    new IDisposable
                    with member _this.Dispose () = printfn "DISPOSED 3"
                }
            try
                do printfn "BEFORE DISPOSE 3"
                return! text "Hi 3" next ctx
            finally
                x.Dispose()
        }
```

... and indeed I could reproduce the same problem here as well.

I will further investigate and try to fix it asap.

Maybe @gerardtoconnor  can even help as well :)

**Comment by TheAngryByrd** [comment]
Seems like the unit tests are covering some disposable cases.  Can we write a test to expose this?

**Comment by gerardtoconnor** [comment]
Ugh ... Task CE coming back to bite me once again.

I will look into this tonight, I think we need to switch to explicit un-try-wrapped disposable instead of using try-finally as it's a bit of a hack but deciding the limitation of the scope given the CPS format complicates the matter but I'm sure we can figure out ... 

I have been having some thoughts on restructuring the task CE a bit, having the CE return a state-machine rather than the task so that we can explicitly control cancellation inheritance, disposables chain as well as re-using state-machine between computations (so a lot less allocations). CE would overload to accept both task-like tasks (like now) as well as parent state-machine, returning the state machine such that in middleware, the return can just be a simple state machine `.Task` property.

I know we don't want to complicate the task CE model but we need to weigh up the benefits of a fully controlled and efficient construct vs what we have now.

**Comment by dustinmoris** [comment]
@gerardtoconnor I'll also have a look at this today.. let me know if you need a hand or message me on Slack if there's anything I can help with.

**Comment by dustinmoris** [comment]
Moved to https://github.com/rspeele/TaskBuilder.fs/issues/9

**Comment by dustinmoris** [comment]
This bug has been fixed in newest TaskBuilder.fs
